name: Build Pet Clinic App
on:
  push:
    branches:
    - main
jobs:


  integration:
    runs-on: private-windows
    steps:
    - name: Clone Selenium Tests
      id: clone-ops
      uses: actions/checkout@v2
      with:
        repository: 'rattisyam/spring-petclinic-selenium'
        ref: 'main'
        token: ${{ secrets.GITOPS_TOKEN }}

    - name: download artifact
      run: jfrog rt dl "petclinic/petclinic/*.jar"  --url https://sixartifacts.jfrog.io/artifactory --apikey ${{ secrets.JFROG_APIKEY }}

    - name: Deploy petclinic
      shell: powershell
      run: $file=Get-ChildItem -Path .\petclinic\ | select name -ExpandProperty Name;
           javaw -jar .\petclinic\$file;

    - name: Run Selenium Tests
      run: spring-petclinic-selenium\.mvnw clean install