name: Build Pet Clinic App
on:
  push:
    branches:
    - main
jobs:
 

    run-jmeter-test:
        runs-on: ubuntu-latest
        #needs: run-integration-test
        env:
            JF_ARTIFACTORY_1: ${{ secrets.JFROG_JWT_TOKEN }}
        steps:
        - uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - uses: jfrog/setup-jfrog-cli@v1          
        - uses: actions/checkout@v2
          
        - run: |           
            jfrog rt dl "petclinic/petclinic/*.jar" --sort-by=created --sort-order=desc --limit=1 --url https://sixartifacts.jfrog.io/artifactory --apikey ${{ secrets.JFROG_APIKEY }}

        - name: Deploy petclinic and test       
          run: javaw -jar ./petclinic/*.jar;
              .\mvnw clean install;
        
        - name: Jmeter Test
          uses: rbhadti94/apache-jmeter-action@v0.3.1
          with:
            testFilePath: src/test/jmeter/petclinic_test_plan.jmx
            outputReportsFolder: target/jmeter/jmeter.csv
     
        




