name: Build Pet Clinic App
on:
  push:
    branches:
    - main
jobs:
    prepare-integration-env:
      runs-on: ubuntu-latest
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUB }}
        ARM_TENANT_ID: ${{ secrets.AZ_TENANT }}
        ARM_CLIENT_ID: ${{ secrets.AZ_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.AZ_SECRET }}
      steps:
      - uses: hashicorp/setup-terraform@v1
      - name: Clone Terraform Repo
        id: clone-ops
        uses: actions/checkout@v2        
        with:
          repository: 'rattisyam/iaac'
          ref: 'main'
          token: ${{ secrets.GITOPS_TOKEN }}
      - run: pwd
      - run: ls -l

      - name: Execute Terraform Templates     
        run: |
          cd ./integration;
          terraform init
          terraform validate
          terraform plan
          terraform apply -auto-approve
        
      
     
        




