name: Build Pet Clinic App
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      


    - name: publish to artifactory
      uses: advancedcsg-open/action-jfrog-cli@master
      with:
        url: 'https://sixartifacts.jfrog.io/'
        credentials type: 'apikey'
        apikey: ${{ secrets.JFROG_APIKEY }}
        args: u "./target/*.jar" petclinic --recursive=false 