name: Build Master branch
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    #if: ${{github.event.head_commit.committer.username != 'web-flow' }}
    steps:
    - uses: actions/checkout@v2      
    - name: Use Node.js ${{ matrix.node-version }}
  
